apiVersion: v1
kind: Secret
metadata:
  name: campconnect-secrets
  namespace: production
type: Opaque
stringData:
  mysql-root-password: "RootPass123"
  mysql-password: "CampPass123"
  mysql-database: "campconnect"
  jwt-secret: "CampConnectJwtSecretKey2025MinLength32Chars"